
-- ROSTER additions
ALTER TABLE public.roster
  ADD COLUMN IF NOT EXISTS jersey_number TEXT,
  ADD COLUMN IF NOT EXISTS photo_url TEXT,
  ADD COLUMN IF NOT EXISTS permission_status TEXT NOT NULL DEFAULT 'pending';

-- SCHEDULE_EVENTS additions
ALTER TABLE public.schedule_events
  ADD COLUMN IF NOT EXISTS event_type TEXT NOT NULL DEFAULT 'game',
  ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES public.schedule_events(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS event_time TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS opponent TEXT,
  ADD COLUMN IF NOT EXISTS end_date DATE;

-- CLIPS additions
ALTER TABLE public.clips
  ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT 'play',
  ADD COLUMN IF NOT EXISTS broll_type TEXT,
  ADD COLUMN IF NOT EXISTS vibe TEXT,
  ADD COLUMN IF NOT EXISTS player_tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS trim_start NUMERIC,
  ADD COLUMN IF NOT EXISTS trim_end NUMERIC,
  ADD COLUMN IF NOT EXISTS permission_cleared BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS suggested_event_id UUID;

-- RECAPS additions
ALTER TABLE public.recaps
  ADD COLUMN IF NOT EXISTS mix_individual INTEGER NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS mix_team_broll INTEGER NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS mix_fan INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS mix_full_game INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS render_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS recap_type TEXT NOT NULL DEFAULT 'season';
